services:
  cv_analyzer:
    build: .
    cpus: 1.5
    mem_limit: 1024m
    mem_reservation: 512m
    pids_limit: 128
    ports:
      - "8003:8003"
    restart: always
    env_file:
      - ./environment/.env.staging
    environment:
      UVICORN_WORKERS: "2"
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      NUMEXPR_NUM_THREADS: "1"
    volumes:
      - ./main.py:/app/main.py
      - ./app:/app/app
      - ./logs:/app/logs
    networks:
      - apigateway_internal_network

networks:
  apigateway_internal_network:
    external: true
